### ISSUE TITLE
Error while starting server

### ISSUE THREAD

**Issue by Mordexxxx** [timing1337/saturnine#7]
Hi, when i try to start saturnine with "py -m saturnine" i get this error
_**Error_read: scene3_point_test.json
Error_read: scene50000_point.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Agust\Downloads\saturnine\saturnine__main.py", line 6, in <module>
    gameserver = GameServer("localhost", 22102)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Agust\Downloads\saturnine\game_server__init.py", line 70, in init
    self.host = enet.Host(enet.Address(host, port), 10, 0, 0, 0)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "enet.pyx", line 262, in enet.Address.init
  File "enet.pyx", line 296, in enet.Address.host.set
TypeError: expected bytes, str found**_

How can i fix that? Thanks :)

**Comment by timing1337** [comment]
could be a problem with resources..? try deleting your server_data

**Comment by lilmayofuksu** [comment]
doubt it

**Comment by timing1337** [comment]
no response
